# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CivilTools
                                 A QGIS plugin
 Herramientas para ingeniería civil y Civil 3D
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-20
        copyright            : (C) 2026 by MM CHATGPT
        email                : MARTIN@EXAMPLE.ORG
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CivilTools class from file CivilTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .civil_tools import CivilTools
    return CivilTools(iface)
